from collections import defaultdict
from game_simulator import *
import itertools

def play(team1, team2, state, model, table):
    """
    generates the result of team1 vs team2
    updates table and records the result in matches
    """
    g1,g2 = play_game(team1, team2, state, model)
    # store matches for revisiting when computing ranking of tied teams
    #matches[(team1,team2)] = {team1: g1, team2:g2}
    # update table
    update_table(team1, team2, g1, g2, table)

def update_table(team1, team2, g1, g2, table):
    table[team1]["GF"] += g1
    table[team1]["GA"] += g2
    table[team2]["GF"] += g2
    table[team2]["GA"] += g1
    if (g1>g2):
        table[team1]["W"] += 1
        table[team2]["L"] += 1
    elif (g1<g2):
        table[team2]["W"] += 1
        table[team1]["L"] += 1
    else:
        table[team1]["D"] += 1
        table[team2]["D"] += 1

def run_season(state, model, games_played = None, games_to_play = None):
    """
    simulates a single league season
    using invariant data in state
    and game simulation model
    optionally: can use results in games_played
                and only simulate matches in games_to_play
                if games_to_play is None then the remaining fixtures are generated by itertools permutations
    returns the final league table
    """
    tie = 0
    ts = state["teams"]
    #table = defaultdict(lambda: {"W": 0, "D": 0, "L": 0, "GF": 0, "GA": 0, "GD": 0, "PTS":0})
    table = defaultdict(lambda: {"W": 0, "D": 0, "L": 0, "GF": 0, "GA": 0})
    #matches = {}

    if games_played is not None:
        for (team1, team2), (score1, score2) in games_played.items():
            update_table(team1, team2, score1, score2, table)
        games_played_set = set(games_played)
    else:
        games_played_set = set()
        
    if games_to_play is None:
        games_to_play = set( itertools.permutations(ts,2) ) - games_played_set

    for team1, team2 in games_to_play:
            play(team1, team2, state, model, table)

    # finalise table
    # taking into account historical rules 
    for team in ts:
        if state["goal_separator"] == "difference":
            table[team]["GD"] = table[team]["GF"] - table[team]["GA"]
        else:
            table[team]["GD"] = table[team]["GF"] / table[team]["GA"]
        table[team]["PTS"] = state["points_per_game"]*table[team]["W"] + table[team]["D"]

    table = list(sorted(table.items(),
        key=lambda item: (item[1]["PTS"], item[1]["GD"], item[1]["GF"]
        ), reverse=True))

    return table

def update_results(table, team_results):
    """
    input: table = list of tuples (team name, dict {W, D, L, GF, GA, GD, PTS})
           results = dict of dicts
    """
    for i, team_data in enumerate(table):
        team = team_data[0]
        stats = team_data[1]
        #pts = stats["PTS"]
        team_results[team][i+1] += 1
        for k, v in stats.items():
            if k in ["PTS", "W", "D", "L", "GF", "GA"]:
            #if k in ["PTS", "W", "D", "L", "GF", "GA", "GD"]:
                team_results[team][k] += v
