from time import perf_counter
import itertools
import numpy as np
from config import *
from rating_model import get_new_ratings

rng = np.random.default_rng()

# lookup table for ratings diff to win expectancy
diff_to_w = np.array([round(1/( 10**(-diff/400)+1),2) for diff in range(-2000, 2001)])

# lookup table for win expectancy to lam1
# indexed from w = 0,0.01,...0.99, 1
w_to_lam1 = np.array( [0.22, 0.21, 0.2, 0.23, 0.21, 0.3, 0.31, 0.31, 0.38, 0.36, 0.42, 0.48, 0.44, 0.49, 0.44, 0.49, 0.43, 0.48, 0.41, 0.45, 0.49, 0.41, 0.45, 0.49, 0.52, 0.43, 0.47, 0.5, 0.54, 0.58, 0.61, 0.65, 0.68, 0.72, 0.76, 0.79, 0.83, 0.87, 0.91, 0.95, 0.99, 1.02, 1.06, 1.1, 1.15, 1.19, 1.23, 1.27, 1.31, 1.36, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.6, 1.6, 1.6, 1.6, 1.8, 1.8, 1.8, 2.0, 2.0, 2.2, 2.2, 2.4, 2.4, 2.6, 2.6, 2.6, 2.8, 2.8, 3.0, 3.2, 3.2, 3.6, 4.0, 4.8, 6.8])

# lookup table for goal difference adjustment factor
gd_adj = np.array( [1,1,1.5,1.75] + [1.75 + (N-3)/8 for N in range(4,50)] )

def update_table(team1, team2, g1, g2, table):
    """
    update individual league table
    """
    table[team1]["GF"] += g1
    table[team1]["GA"] += g2
    table[team2]["GF"] += g2
    table[team2]["GA"] += g1
    if (g1>g2):
        table[team1]["W"] += 1
        table[team2]["L"] += 1
    elif (g1<g2):
        table[team2]["W"] += 1
        table[team1]["L"] += 1
    else:
        table[team1]["D"] += 1
        table[team2]["D"] += 1
        
def run_season_vec(
        season,
        ratings,
        home_adv,
        Nsims, 
        model,
        games_played = None,
        games_to_play = None,
    ):
    """
    vectorised monte carlo simulation
    inputs:
    season - determines points per game and goal av/diff
    ratings - dict of team ratings
    home adv - season home adv modifier
    Nsims - number of simulations
    model - sets whether to update Elo or not
    games_played - historical results to take into account before simulating
    games_to_play - matches to simulate. if None, then the remaining fixtures are generated by itertools permutations

    outputs:
    returns averaged results and positions
    """
        
    start = perf_counter()
    print(f"\nSimulating league with game model: {model} - vectorised")

    # initialise an empty league table  
    start_table = { team: {"W": 0, "D": 0, "L": 0, "GF": 0, "GA": 0}  for team in ratings}
    
    if games_played:
        # run historical results and update table and ratings
        # no vectorisation 
        for (team1, team2), (score1, score2) in games_played.items():
            ratings[team1], ratings[team2], _ = get_new_ratings( ratings | {"home_adv": home_adv}, team1, team2, score1, score2)
            update_table(team1, team2, score1, score2, start_table) 

        games_played_set = set(games_played)

        #print("Table at simulation start:", start_table)
        #print("Ratings at table start:", ratings)
    else:
        # no historical results
        games_played_set = set()
        
    if games_to_play is None:
        # do not have fixture list - just generate all remaining fixtures out of order
        games_to_play = list( set( itertools.permutations(ratings.keys(),2) ) - games_played_set )
        
    # vectorise and simulate
    team_stats = {}
    for team, stat in start_table.items():
        team_stats[team] = {
            "W": np.full(Nsims, stat["W"], dtype=int),
            "D": np.full(Nsims, stat["D"], dtype=int),
            "L": np.full(Nsims, stat["L"], dtype=int),
            "GF": np.full(Nsims, stat["GF"], dtype=int),
            "GA": np.full(Nsims, stat["GA"], dtype=int),
            "rating": np.full(Nsims, ratings[team], dtype=int)
        }
    
   # loop over fixtures
    for team1, team2 in games_to_play:
        #print(team1, team2)
        diff = team_stats[team1]["rating"] - team_stats[team2]["rating"] + home_adv
        #print(diff)
        wex1 = diff_to_w[diff+2000]
        wex1_lookup = (100*wex1).astype(int)
        #print(wex)
        lam1 = w_to_lam1[wex1_lookup]
        lam2 = w_to_lam1[100-wex1_lookup]
        #print(lam1, lam2)
        g1 = rng.poisson(lam1, Nsims)
        g2 = rng.poisson(lam2, Nsims)
        #print(team1, g1)
        #print(team2, g2)

        t1_wins = g1 > g2
        t2_wins = g2 > g1
        draws = g1 == g2
        
        team_stats[team1]["W"] += np.where( t1_wins, 1, 0)
        team_stats[team1]["D"] += np.where( draws, 1, 0)
        team_stats[team1]["L"] += np.where( t2_wins, 1, 0)
        team_stats[team1]["GF"] += g1
        team_stats[team1]["GA"] += g2

        team_stats[team2]["W"] += np.where( t2_wins, 1, 0)
        team_stats[team2]["D"] += np.where( draws, 1, 0)
        team_stats[team2]["L"] += np.where( t1_wins, 1, 0)
        team_stats[team2]["GF"] += g2
        team_stats[team2]["GA"] += g1

        # update ratings
        if model == "elo_dynamic":
            margin = abs(g1 - g2).astype(int)
            K = 20
            G = gd_adj[margin]
            outcome1 = np.where(t1_wins, 1.0, np.where(draws, 0.5, 0.0))
            rating_change = K*G*(outcome1 - wex1)
            team_stats[team1]["rating"] += rating_change.astype(int)
            team_stats[team2]["rating"] -= rating_change.astype(int) 

    # Rules for points and goal separation 
    if season < CHANGE_TO_GOAL_DIFF:
        ppg, sep = 2, "GAv"
    elif CHANGE_TO_GOAL_DIFF <= season < CHANGE_TO_THREE_POINTS_PER_WIN:
        ppg, sep = 2, "GD"
    else:
        ppg, sep = 3, "GD"

    for team in team_stats:
        team_stats[team]["PTS"] = ppg*team_stats[team]["W"] + team_stats[team]["D"]
        team_stats[team]["GD"] = team_stats[team]["GF"] - team_stats[team]["GA"]
        team_stats[team]["GAv"] = team_stats[team]["GF"] / team_stats[team]["GA"]

    teams = list(team_stats.keys())
    league_size = len(teams)

    # stack points and goal separation criterion
    points = np.vstack([team_stats[t]["PTS"] for t in teams])
    goal_sep = np.vstack([team_stats[t][sep] for t in teams])
    goal_for = np.vstack([team_stats[t]["GF"] for t in teams])
    # sorting criteria
    # criteria are applied from right to left
    sortings = np.lexsort((-goal_for, -goal_sep, -points), axis=0)
    final_pos = np.argsort(sortings, axis=0) + 1
    # if sortings[i] is j then sortings[j] is ith smallest element of sortings
    # final_pos[k] is l then sorted_team_indices[l] is kth smallest element of sorted_team_indices
    # the elements of sorted_team_indices are indices of sortings, so sorted_team_indices[l] is k
    # so sortings[k] is the lth smallest element of sortings
    # so final_pos[k] gives the rank l of k (modulo index starting at 0)
    
    for i, team in enumerate(teams):
        team_stats[team]["POS"] = final_pos[i]
        
    # aggregate and average the results
    results = {}
    for team, stats in team_stats.items():
        results[team] = {}
        for res, data in stats.items():
            results[team][res] = np.mean(data)
        for i in range(1, league_size+1):
            results[team][i] = np.mean(stats["POS"] == i)

    results = { k:v for k,v in sorted(results.items(), key = lambda item: -item[1]["PTS"]) }

    elapsed = perf_counter() - start
    print(f"Simulation finished in {elapsed:.6f}s\n")

    return results
    
